apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: cluster-configuration-policy
  namespace: cluster-configuration
spec:
  complianceType: musthave
  remediationAction: enforce
  disabled: false
  namespaces:
    exclude: ["kube-*"]
    include: ["default"]
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: imageregistry.operator.openshift.io/v1
        kind: Config
        metadata:
          name: cluster
        spec:
          managementState: Managed
          replicas: 1
          logging: 2
          storage:
            emptyDir: {}
          pvc:
            claim:
