apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: cvo-policy
  namespace: cluster-configuration
spec:
  complianceType: musthave
  remediationAction: enforce
  disabled: false
  namespaces:
    exclude: ["kube-*"]
    include: ["default"]
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: config.openshift.io/v1
        kind: ClusterVersion
        metadata:
          name: version
        spec:
          channel: stable-4.6
          upstream: https://api.openshift.com/api/upgrades_info/v1/graph
          desiredUpdate:
            version: 4.6.0-fc.8
      remediationAction: enforce
