apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: flexran-nfd
  namespace: flexran-workloads
  labels:
    app: flexran-application
  annotations:
    apps.open-cluster-management.io/github-path: cluster_configuration/sites/sample_site/nfd
spec:
  channel: flexran-workloads/acm-gitops-github
  name: flexran-nfd
  placement:
    placementRef:
      kind: PlacementRule
      name: apply-nfd-to-ready-clusters
      apiGroup: apps.open-cluster-management.io
