apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: cluster-configuration-policy
  namespace: cluster-configuration
  annotations:
    policy.mcm.ibm.com/standards: NIST-CSF
    policy.mcm.ibm.com/categories: PR.IP Information Protection Processes and Procedures
    policy.mcm.ibm.com/controls: PR.IP-1 Baseline configuration

