apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: cvo-policy
  namespace: cluster-configuration
placementRef:
  name: cvo-rule
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: cvo-policy
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cvo-rule
  namespace: cluster-configuration
spec:
  clusterConditions:
  - type: OK
