apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-performance-to-ready-clusters
  namespace: flexran-workloads
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
