apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acm-gitops-github
  namespace: flexran-workloads
  annotations:
    apps.open-cluster-management.io/webhook-enabled: "true"
    apps.open-clustermanagement.io/webhook-secret: webhooksecret
spec:
  type: GitHub
  pathname: https://github.com/redhat-nfvpe/flexran-manifests.git
