apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-flexran-common-workloads-to-ready-clusters
  namespace: flexran-workloads
spec:
  clusterConditions:
    - type: OK
  clusterSelector:
    matchExpressions: []
