apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-quorum-guard
  namespace: openshift-machine-config-operator
  unmanaged: true
spec:
  replicas: 2
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: etcd-quorum-guard
        name: etcd-quorum-guard
  selector:
    matchLabels:
      k8s-app: etcd-quorum-guard


