apiVersion: v1
kind: Pod
metadata:
  name: sriov-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-network
spec:
  nodeSelector:
    kubernetes.io/hostname: master-0
  containers:
  - name: sriov-container
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
