apiVersion: v1
kind: Pod
metadata:
  name: sriov-pod
  namespace: openshift-sriov-network-operator
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-network
spec:
  containers:
  - name: sriov-container
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
