apiVersion: v1
kind: Pod
metadata:
  name: multus-example-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: additional-network
spec:
  containers:
  - name: multus-example-pod
    command: ["ifconfig"]
    image: centos/tools
    stdin: true
    tty: true
