apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- channel/namespace.yaml
- channel/channel.yaml
- rule/placement_rule_nfd.yaml
- rule/placement_rule_performance_profile.yaml
- rule/placement_rule_ptp.yaml
- subscription/sub_nfd.yaml
- subscription/sub_performance_profile.yaml
- subscription/sub_ptp.yaml

