apiVersion: v1
kind: Pod
metadata:
  name: cnf-tests
spec:
  containers:
  - name: cnf-tests
    image: quay.io/openshift-kni/cnf-tests
    command: ['/usr/bin/test-run.sh', '-ginkgo.focus=performance']
    tty: true
    volumeMounts:
    - mountPath: /kubeconfig
      name: auth-volume
    env:
      - name: KUBECONFIG
        value: /kubeconfig
      - name: ROLE_WORKER_CNF
        value: master
  volumes:
  - name: auth-volume
    hostPath:
      path: /root/clusterconfigs/auth/kubeconfig
      type: File
