apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: flexran
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - flexran-performance
      - flexran-multus-networks
      - flexran-nfd
