apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: additional-network
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "name": "eno2",
    "mode": "bridge",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "192.168.2.100/24",
          "gateway": "192.168.2.1"
        }
      ]
    } 
  }'
