apiVersion: v1
kind: Pod
metadata:
  labels:
    app: flexran-lte-pod
  name: flexran-lte-pod
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: flexran:latest
    imagePullPolicy: IfNotPresent
    name: flexran-container1
    resources:
      limits:
        cpu: "4"
        hugepages-1Gi: 16Gi
        intel.com/intel_fec: "1"
        memory: 16Gi
      requests:
        cpu: "4"
        hugepages-1Gi: 16Gi
        intel.com/intel_fec: "1"
        memory: 16Gi
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
        - IPC_LOCK
        - SYS_NICE
        - SYS_ADMIN
      privileged: false
    tty: true
    volumeMounts:
    - mountPath: /mnt/huge
      name: hugepage
    - mountPath: /sys/
      name: sys
  volumes:
  - emptyDir:
      medium: HugePages
    name: hugepage
  - hostPath:
      path: /sys
      type: ""
    name: sys

