apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-rl-to-ready-clusters
  namespace: openshift-resource-locker
spec:
  clusterConditions:
    - type: OK
  clusterSelector:
    matchExpressions: []
