apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: cluster-configuration-policy
  namespace: cluster-configuration
  annotations:
    policy.mcm.ibm.com/standards: NIST-CSF
    policy.mcm.ibm.com/categories: PR.IP Information Protection Processes and Procedures
    policy.mcm.ibm.com/controls: PR.IP-1 Baseline configuration
spec:
  complianceType: musthave
  remediationAction: enforce
  disabled: false
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Node
        metadata:
          name: slave-master-0
          labels:
              cpumanager: "true"
              ptp/grandmaster: ""
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Node
        metadata:
          name: slave-master-1
          labels:
              cpumanager: "true"
              ptp/grandmaster: ""
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Node
        metadata:
          name: slave-master-2
          labels:
              cpumanager: "true"
              ptp/grandmaster: ""

