---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: flexran-performance
  namespace: flexran-workloads
  labels:
    app: flexran-applications
  annotations:
    apps.open-cluster-management.io/github-path: cluster_configuration/sites/sample_site/performance_profile/
    apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: flexran-workloads/acm-gitops-github
  name: flexran-performance
  placement:
    placementRef:
      kind: PlacementRule
      name: apply-performance-to-ready-clusters
      apiGroup: apps.open-cluster-management.io
