apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- sriov/sriov_network_node_policy.yaml
patchesStrategicMerge:
- performance_profile/custom_settings.yaml
- ptp/custom_settings.yaml

