apiVersion: v1
kind: Namespace
metadata:
  labels:
          openshift.io/run-level: "1"
  name: resource-locker
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: resource-locker-operator
  namespace: resource-locker
spec:
  targetNamespaces:
  - resource-locker
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: resource-locker-operator
  namespace: resource-locker
spec:
  channel: alpha
  name: resource-locker-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
