apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: endpoint-operator
  namespace: multicluster-endpoint
spec:
  selector:
    matchLabels:
      name: endpoint-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: endpoint-operator
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
        - name: OPERATOR_NAME
          value: endpoint-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: IMAGE_TAG_POSTFIX
        - name: USE_SHA_MANIFEST
          value: "true"
        image: registry.redhat.io/rhacm1-tech-preview/endpoint-rhel8-operator@sha256:970fb1bb2f481d82d171464803d21c1ceed8f9034889fd74d8f5a9b433a8216a
        imagePullPolicy: Always
        name: endpoint-operator
        resources: {}
      imagePullSecrets:
      - name: acm-pull-secret
      serviceAccountName: endpoint-operator
status: {}
