apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: ran-performanceprofile
spec:
  additionalKernelArgs:
  - "processor.max_cstate=1"
  - "intel_idle.max_cstate=0"
  - "intel_pstate=disable"
  - "idle=poll"
  - "intel_iommu=off"
  - "selinux=0"
  - "enforcing=0"
  - "nmi_watchdog=0"
  - "audit=0"
  - "mce=off"
  - "kthread_cpus=0"
  - "irqaffinity=0"
  - "nosoftlockup"
  - "skew_tick=1"
  - "nohz=on"
  - "nohz_full=2-9"
  - "rcu_nocbs=2-9"
  cpu:
    isolated: "2-9"
    reserved: "0-1"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
      node: 0
  realTimeKernel:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
