apiVersion: v1
kind: Pod
metadata:
  name: cpumanager-pod
spec:
  containers:
  - name: cpumanager
    image: centos/tools
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: 1
        memory: "1G"
      limits:
        cpu: 1
        memory: "1G"
  nodeSelector:
    cpumanager: "true"
